# Generated by Django 6.0.6 on 2026-06-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srt_flower_marchent', '0003_garland_flower_garland'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='flowers/thumbs/'),
        ),
    ]
